### ISSUE TITLE
ThunderbirdTray stopping other applications closing

### ISSUE THREAD

**Issue by GavinBrelstaff** [TheGuardianWolf/ThunderbirdTray#14]
I installed ThunderbirdTray v1.4.0 on WIn10 64bit  
using the  recommended NET Framework release and it runs fine!
-- except 
that while it runs it prevents an application other than Thunderbird for being closed 
i.e. my favorite old version of TotalRecorder (v7.1) from way back when.

As soon as I exit ThunderbirdTray  I can close my TotalRecorder  application.

Is it possible that ThunderbirdTray is stopping the exit of any application beginning with the letter T?

**Comment by TheGuardianWolf** [comment]
When you say being closed, I assume you mean clicking the 'X'?

I'm not able to stop the exiting of applications, otherwise I'd have implemented it for Thunderbird.  Windows does not allow the interception of termination signals sent to another application unless you inject code into the other application.

I can't see how the issues are related unfortunately.

The application has two interactions that reach outside of itself, one is the automation api that is used to hook into Thunderbird - it only touches one window so if TB is working, nothing else is affected. The other is the global mutex that stops two instances from running at once. This mutex is highly unlikely to affect anything since I generated the GUID randomly...

With a quote from https://www.guidgenerator.com/:

"if every human on Earth generated 600,000,000 GUIDs there would only be a 50% probability of a duplicate"

**Comment by TheGuardianWolf** [comment]
I'm closing this for now as there's no further way to diagnose this, please re-open if you manage to get more information about this behavior.
