### ISSUE TITLE
Thunderbird Tray does not start Thunderbird if executable is not in usual location

### ISSUE THREAD

**Issue by matthewsheeran** [TheGuardianWolf/ThunderbirdTray#23]
Starting ThunderbirdTray before Thunderbird is problematic. (Multiple Monitors work well for me though.)
I am using Thunderbird Portable from PortableApps however with the Minimize on Close Extension installed.

**Comment by TheGuardianWolf** [comment]
Unfortunately this wasn't designed for the portable version because your executable isn't where I would expect it to be, in your case you will have to launch it afterwards so it can attach.

What I can do in a new release is give you a setting to set the executable location, how does that sound?

This would have some benefit to people not installing in the usual location as well.

**Comment by TheGuardianWolf** [comment]
Just waiting for me to test and release this now

**Comment by TheGuardianWolf** [comment]
Works
