### ISSUE TITLE
Start more than once for different TB

### ISSUE THREAD

**Issue by Bodenseematze** [TheGuardianWolf/ThunderbirdTray#26]
I use several (portable) Thunderbird installations to split my personal and business accounts.
So it would be really nice if I could start several instances of the ThunderbirdTray for each of them.

If this will be made possible it additionally should show some different information at the icons tooltip (e.g. the first account name? Or better: some user defined string) to differentiate between the instances...

**Comment by TheGuardianWolf** [comment]
I'd like to do this but it's too complex for the scope of this particular application. I had another thing I tried before that would have been capable but I scrapped it since I didn't have time to maintain it. The key to the success of this particular application is my relatively simple scope.

It also turns out that other people have made similar things, although mine had separate tray icons for each application you registered. Try out the following:

https://www.ghacks.net/2020/03/28/minimize-any-program-to-the-system-tray-with-minimizetotray/

If you're still interested in something more after using it, then give me your thoughts on that application's usability
