### ISSUE TITLE
Is it possible to adapt the icon when there is a new message?

### ISSUE THREAD

**Issue by YildirayJuelz** [TheGuardianWolf/ThunderbirdTray#28]
Hello,

thanks for the app! It's great. I was able to adapt it so I could also put the whatsapp app for windows into the tray. So now your program runs twice and I even put it in autorun 👍 
(I basically only did a find and replace for the word "thunderbird", changed the path and icon. The only challenge was to link the correct process to the app ;) )

Now I am looking for an option for how I can change the tray icon if there is a new unread message (when the app is not minimized there icon in the taskbar changes and shows the number of unread messages. I'd love to see the same for the tray icon. Could also be interesting for thunderbird maybe)
Do you have an idea how I could implement that? The first problem for me is to even make the programm notice that there is a new message...
I don't know much about coding in c# and windows applications so I'm kind of stuck now.
Any help would be appreciated ;)

**Comment by TheGuardianWolf** [comment]
I see you found the secret to coding with find and replace 😆 

I'm not going to support this use case but I can point you in the correct direction. Before Thunderbird moved to WebExtensions, plugins were able to make Windows platform calls such as those that I use to minimise to tray.

Now that it's no longer possible, we need to create two separate parts to implement that sort of functionality.

WebExtensions can be made to work with a companion application. One like the one you are proposing. In short you have to make a Thunderbird plugin and make it communicate with your Windows application.

There might be a shortcut, if you can locate the resource that the taskbar icon uses, you can steal it and update the Thunderbird tray icon to use that one.

All this might be a bit of a moot point though, have you not got this option?

![Screenshot 2021-02-21 235614](https://user-images.githubusercontent.com/8168401/108622865-79ae7d80-74a0-11eb-84a9-f35c2df9c6a9.png)

In fact this app seems to be obsolete with their latest versions of Thunderbird - they include a minimize to tray option. I've actually switched to Outlook due to calendar issues so I personally don't use it much anymore.

**Comment by YildirayJuelz** [comment]
> In fact this app seems to be obsolete with their latest versions of Thunderbird - they include a minimize to tray option.

Great! I found the option and it works! So at least for thunderbird I won't need "ThunderbirdTray" anymore ;)
Thanks!

The whole icon thing would just be some playing around anyway. But I would still love it if it worked.

> There might be a shortcut, if you can locate the resource that the taskbar icon uses, you can steal it and update the Thunderbird tray icon to use that one.

Yes! That's exactly what I was trying to do when I started my last try (a few month ago). But I wasn't able to find an option how to get access to the taskbar icons.
Maybe I'll find the time and the passion to start another try in the next time.

This was my last approach by the way:
https://stackoverflow.com/questions/32001224/how-to-get-the-windows-store-app-icon-from-a-hwnd
https://stackoverflow.com/questions/32001621/how-to-get-the-application-name-from-hwnd-for-windows-10-store-apps-e-g-edge

> I'm not going to support this use case but I can point you in the correct direction.

Sure. I never expected you to. You already helped a lot and if you know some more tips about the "shortcut" --> let me know! 👍
